title: LOLO' LINKS

links:
  - Search Pages:
      - ICON: search.svg
      - Google: https://google.com
      - stack overflow: https://stackoverflow.com
      - GitHub: https://github.com
      - 必应: https://bing.com
      - 知乎: https://www.zhihu.com
      - 百度: https://baidu.com

  - Unity:
      - ICON: unity.svg
      - Scripting API: https://docs.unity3d.com/2020.3/Documentation/ScriptReference/index.html
      - YAML Class ID Reference: https://docs.unity3d.com/2020.3/Documentation/Manual/ClassIDReference.html
      - Define Directives: https://docs.unity3d.com/Manual/PlatformDependentCompilation.html
      - http://dotween.demigiant.com/documentation.php
      - EmmyLua Doc: https://emmylua.github.io
      - Unity Download Archive: https://unity3d.com/get-unity/download/archive
      - Unity Cracking: https://appnee.com/unity
      - Android Support Code: https://android.googlesource.com/platform/frameworks/support/+/79398eaefea45e61d839cf4e0534f0eafee70a09/v4/java/android/support/v4
      - Unity Editor Icons: https://gist.github.com/masa795/5797164

  - Node / JS / Web:
      - ICON: javascript.svg
      - NodeJS API: http://nodejs.cn/api
      - ECMAScript 6: https://es6.ruanyifeng.com
      - fs-extra: https://juejin.cn/post/6844903641594216455
      - cheerio: https://github.com/cheeriojs/cheerio
      - VUE: https://cn.vuejs.org/v2/guide/index.html
      - Electron: https://wizardforcel.gitbooks.io/electron-doc/content/
      - Element: https://element.eleme.cn/#/zh-CN/component/installation
      - Ant Design Vue: https://next.antdv.com/components/overview-cn
      - React: https://zh-hans.reactjs.org/docs/getting-started.html
      - Material-UI: https://mui.com/zh/getting-started/usage/
      - Webpack: https://fakefish.github.io/react-webpack-cookbook/Introduction-to-Webpack.html

  - C# / C / C++:
      - ICON: cpp.svg
      - .NET API: https://docs.microsoft.com/zh-cn/dotnet/api/?view=netstandard-2.1
      - C++ 教程: https://www.runoob.com/cplusplus/cpp-environment-setup.html
      - LCUI: https://github.com/lc-soft/LCUI

  - Codes:
      - ICON: terminal.svg
      - Hello GitHub: https://hellogithub.com/
      - Python 教程: https://docs.python.org/zh-cn/3/tutorial/index.html
      - PyTorch 教程: https://pytorch.apachecn.org
      - MacOS Anaconda PyTorch: https://blog.csdn.net/libing_zeng/article/details/96615716

  - NAS / VPS:
      - ICON: nas.svg
      - Vultr: https://www.vultr.com
      - NameSilo: https://www.namesilo.com
      - TencentCloud Lighthouse: https://cloud.tencent.com/product/lighthouse
      - 阿里云: https://www.aliyun.com/
      - V2Ray geoip.dat: https://github.com/Loyalsoldier/v2ray-rules-dat
      - Synology Archive Download: https://archive.synology.com/download
      - 射手网（伪）: https://assrt.net/
      - https://movie.douban.com/
      - https://www.themoviedb.org
      - 阿里小站: https://alixiaozhan.net/
      - 阿里云盘小站: https://aliyunshare.cn/
      - https://aliyun.panpanr.com/
      - 阿里盘搜: https://www.alipanso.com/
      - K-POP MP3: http://ilkpop.com/index.xhtml
      - My Free MP3: http://tool.liumingye.cn/music/?page=searchPage
      - 小白盘（MP3）: https://www.xiaobaipan.com/
      - 霸王龙压制组: https://t-rex.tzfile.com/
      - 阿里云盘资源汇总: https://docs.qq.com/sheet/DVHpJVmRhT3ViV09Q?tab=ppx5bp
      - 单机游戏: https://www.aliyundrive.com/s/F15T9aT6wXu
      - 基地 S01: https://www.aliyundrive.com/s/G1Vj2k2jjc6/folder/614d62a3e6637d2ecde747ab903a8239b8392595
      - 早间新闻 S02: https://www.aliyundrive.com/s/1bhLGnr6sfH/folder/61442e7e63fbb6da1c234883a4fda0fe157b7659
      - 英雄联盟：双城之战: https://www.aliyundrive.com/s/6wj7FkQFpok/folder/6187604545a245eb023d4be6923410bee0d43cd3
      - 黄石 S04: https://www.aliyundrive.com/s/tAz1eLWh2UA/folder/618f4a0bcc0f2848616a4ef690f65ce56a7c6374

  - Resources:
      - ICON: resource.svg
      - 爱给网/模型/资源: https://www.aigei.com/unity3d
      - 阿里矢量图标: https://www.iconfont.cn
      - https://fonts.google.com/icons
      - https://remixicon.com/
      - Google Fonts 中文版: https://www.font.im/
      - Pure.CSS: https://www.purecss.cn/
      - https://getmdl.io

  - Online Tools:
      - ICON: toolbox.svg
      - JSON Viewer: http://jsonviewer.stack.hu
      - Easing functions: https://easings.net
      - 文件转换器: https://convertio.co/zh
      - Fotor Editor - 图像编辑: https://www.fotor.com/photo-editor-app/editor/basic

  - Bookmark:
      - ICON: bookmark.svg
      - https://zh.wikipedia.org
      - https://www.uwa4d.com
      - 书栈网: https://www.bookstack.cn
      - https://tobiasahlin.com/spinkit/
      - https://flukeout.github.io/
      - https://cssgrid-generator.netlify.app/

  - Read Later:
      - ICON: book.svg
      - KCP Protocol: https://github.com/skywind3000/kcp
      - VPS 部署 Hugo: http://www.shashun.site/post/first/
      - Upgrading to Caddy 2: https://caddyserver.com/docs/v2-upgrade
      - 六边形网格: https://blog.csdn.net/icebergkevin/article/details/50173527
      - https://www.redblobgames.com/grids/hexagons/
      - Emby Cracking: http://ilolita945.softether.net:5212/s/adhl?path=%2F
